# Generated by Django 4.2.2 on 2023-06-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0003_movie_description_movie_imdb_rating_movie_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (3, 'Sci-Fi'), (2, 'Comedy'), (0, 'Another'), (4, 'Drama')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='more',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.moreinfo'),
        ),
    ]
