# Generated by Django 4.2.2 on 2023-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0007_alter_moreinfo_genre_alter_moreinfo_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Horror'), (4, 'Drama'), (2, 'Comedy'), (3, 'Sci-Fi'), (0, 'Another')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, '*****'), (0, '*'), (1, '**'), (2, '***'), (3, '****')], default=0, null=True),
        ),
    ]
